# Generated by Django 5.2 on 2025-05-21 01:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
    ]
