# Generated by Django 5.2 on 2025-05-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='blog.blog'),
        ),
    ]
